#
# [CalistisCore - BroadcasterConfiguration]
# [File created on 05/16/2022]
#

#
# The broadcaster task delay in ticks.
#
# 1 sec -> 20 ticks
# 1 min -> 1200 ticks 
#
delay-in-ticks: 1200

#
# The broadcaster messages list.
# Add how much messages you want.
# 
# - {message}
#
broadcaster-messages:
  - §6» §7Mensagem 1
  - §6» §7Mensagem 2
  - §6» §7Mensagem 3
  - §6» §7Mensagem 4
